version: '2'
networks:
  esus-net:
    driver: bridge

services:
  db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=esus
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  pec-app:
    image: ubuntu:latest
    restart: always
    volumes:
      - ./:/pec-docker/
    ports:
      - 8084:8080
    stdin_open: true
    tty: true
    #entrypoint: ["entrypoint.sh"]
    working_dir: /pec-docker/
    mem_limit: 4g
    depends_on:
      - db

volumes:
  db:
